### ISSUE TITLE
How to get API KEY

### ISSUE THREAD

**Issue by huylv177** [kudan-eu/Simple-Samples-Android#4]
I have integrated kudan to my new AR app, but it requires API KEY for function setAPIKey(). So i just want to ask how to get a new API key? Thank you!

**Comment by eddy-kudan** [comment]
You would need to buy a license in order to use your own custom bundle ID. Alternatively whilst the app is in development you can use one of the bundleID+key combinations found at https://wiki.kudan.eu/Development_License_Keys
